### ISSUE TITLE
example of UNFCCCSingleCategoryApiReader

### ISSUE THREAD

**Issue by mfastudillo** [pik-primap/unfccc_di_api#70]
* UNFCCC DI API version: 3.0.2
* Python version: 3.9.13
* Operating System: windows

### Description

I am exploring how to use the library. The documentation is clear on how to use the `UNFCCCApiReader` but it would be nice to add an example for the `UNFCCCSingleCategoryApiReader`. It is not super straight forward.

### What I Did

After some back and forward I manage to get some results with code like this, which returns something meaningful
```python
single_category_reader = unfccc_di_api.UNFCCCSingleCategoryApiReader(party_category='annexOne')
single_category_reader.query(party_codes=['ESP'],category_ids=[9422],measure_ids=[10578])
```
But it would be nice to have an example

**Comment by mikapfl** [comment]
In general, all functionality provided by the `UNFCCCSingleCategoryApiReader` is also provided by the more user-friendly `UNFCCCApiReader`, or at least that is the goal. What is your use case for directly using the single category reader?

**Comment by mikapfl** [comment]
I see, yes, for that use case the single category reader is more efficient as you note. I'll see if I find time to add an example. Pull requests are welcome as well! :slightly_smiling_face:

**Comment by mikapfl** [comment]
Directly using the UNFCCCApiReader is generally broken due to changes in the API at UNFCCC's side. I recommend you use the ZenodoReader instead. It is less flexible, but performance is much better, you can simply filter the results on your side.
